# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'NavSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for NavSwift
	pod 'AlamofireImage', '~> 4.1'
	pod 'Alamofire', '~> 5.0'
	pod "TMDBSwift"

end
